name: noteai
description: "TwinMind AI Dictaphone Clone - AI-powered voice recording with transcription and chat"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Local Database
  realm: ^20.1.1
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.1.1
  
  # Audio Recording
  record: ^6.1.1
  audioplayers: ^6.1.0
  permission_handler: ^12.0.1
  
  # Background Processing
  # workmanager: ^0.5.2  # Temporarily disabled due to build issues
  
  # Network & Connectivity
  connectivity_plus: ^6.1.5
  http: ^1.5.0
  
  # Utilities
  get_it: ^8.2.0
  dartz: ^0.10.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  
  # AI Integration
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mockito: ^5.4.4
flutter:

  uses-material-design: true

  assets:
    - .env