import 'package:http/http.dart' as http;
import 'package:flutter_dotenv/flutter_dotenv.dart';

abstract class OpenAIDataSource {
  Future<String> transcribeAudio(String audioPath);
  Future<String> generateSummary(String transcript);
  Future<String> askQuestion(String question, String context);
}

class OpenAIDataSourceImpl implements OpenAIDataSource {
  final http.Client client;
  final String apiKey;
  final String orgId;
  final bool useMockResponses;
  
  OpenAIDataSourceImpl({http.Client? client, String? apiKey, String? orgId})
      : client = client ?? http.Client(),
        apiKey = apiKey ?? dotenv.env['OPENAI_API_KEY'] ?? 'your_api_key_here',
        orgId = orgId ?? dotenv.env['OPENAI_ORG_ID'] ?? '',
        useMockResponses = dotenv.env['MOCK_AI_RESPONSES']?.toLowerCase() == 'true';
  
  @override
  Future<String> transcribeAudio(String audioPath) async {
    if (useMockResponses) {
      // Mock implementation for development/testing
      await Future.delayed(const Duration(seconds: 2)); // Simulate API call
      return 'This is a mock transcript of the audio recording. In a real implementation, this would be generated by OpenAI Whisper API.';
    }
    
    // TODO: Implement real OpenAI Whisper API call
    // This would make an HTTP request to OpenAI's Whisper API
    throw UnimplementedError('Real OpenAI Whisper API integration not yet implemented');
  }
  
  @override
  Future<String> generateSummary(String transcript) async {
    if (useMockResponses) {
      // Mock implementation for development/testing
      await Future.delayed(const Duration(seconds: 1)); // Simulate API call
      return 'This is a mock summary of the transcript. In a real implementation, this would be generated by OpenAI GPT API.';
    }
    
    // TODO: Implement real OpenAI GPT API call for summarization
    throw UnimplementedError('Real OpenAI GPT API integration not yet implemented');
  }
  
  @override
  Future<String> askQuestion(String question, String context) async {
    if (useMockResponses) {
      // Mock implementation for development/testing
      await Future.delayed(const Duration(seconds: 1)); // Simulate API call
      return 'This is a mock answer to your question: "$question". In a real implementation, this would be generated by OpenAI GPT API based on the context provided.';
    }
    
    // TODO: Implement real OpenAI GPT API call for Q&A
    throw UnimplementedError('Real OpenAI GPT API integration not yet implemented');
  }
}
