// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKaGgLk_Xsoq7S3HhAmfn-mNVW2kl9vQ',
    appId: '1:249255367479:web:e8f2fe07659d283d6f40b2',
    messagingSenderId: '249255367479',
    projectId: 'noteai-23146',
    authDomain: 'noteai-23146.firebaseapp.com',
    storageBucket: 'noteai-23146.firebasestorage.app',
    measurementId: 'G-8BKSN3LRPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTm7lXjHzO3MIqWf-uBw0Cp_iShNOJEWs',
    appId: '1:249255367479:android:cd6730d4a74e60556f40b2',
    messagingSenderId: '249255367479',
    projectId: 'noteai-23146',
    storageBucket: 'noteai-23146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALcmuzJqPawSqF1Ig1yU1AfVblu_Jc1PQ',
    appId: '1:249255367479:ios:87d89fb008f178fa6f40b2',
    messagingSenderId: '249255367479',
    projectId: 'noteai-23146',
    storageBucket: 'noteai-23146.firebasestorage.app',
    iosBundleId: 'dev.devlet.noteai',
  );
}
