import '../../domain/entities/language.dart';

class SupportedLanguages {
  static const List<Language> _languages = [
    // Popular Languages with Country Emojis
    Language(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      region: 'Global',
      script: 'Latin',
      countryEmoji: '🇺🇸',
      isPopular: true,
      sortOrder: 1,
    ),
    Language(
      code: 'zh',
      name: 'Chinese (Simplified)',
      nativeName: '中文 (简体)',
      region: 'Asia',
      script: 'Han',
      countryEmoji: '🇨🇳',
      isPopular: true,
      sortOrder: 2,
    ),
    Language(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇪🇸',
      isPopular: true,
      sortOrder: 3,
    ),
    Language(
      code: 'hi',
      name: 'Hindi',
      nativeName: 'हिन्दी',
      region: 'Asia',
      script: 'Devanagari',
      countryEmoji: '🇮🇳',
      isPopular: true,
      sortOrder: 4,
    ),
    Language(
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
      region: 'Middle East',
      script: 'Arabic',
      countryEmoji: '🇸🇦',
      isPopular: true,
      sortOrder: 5,
    ),
    Language(
      code: 'pt',
      name: 'Portuguese',
      nativeName: 'Português',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇵🇹',
      isPopular: true,
      sortOrder: 6,
    ),
    Language(
      code: 'bn',
      name: 'Bengali',
      nativeName: 'বাংলা',
      region: 'Asia',
      script: 'Bengali',
      countryEmoji: '🇧🇩',
      isPopular: true,
      sortOrder: 7,
    ),
    Language(
      code: 'ru',
      name: 'Russian',
      nativeName: 'Русский',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇷🇺',
      isPopular: true,
      sortOrder: 8,
    ),
    Language(
      code: 'ja',
      name: 'Japanese',
      nativeName: '日本語',
      region: 'Asia',
      script: 'Hiragana',
      countryEmoji: '🇯🇵',
      isPopular: true,
      sortOrder: 9,
    ),
    Language(
      code: 'pa',
      name: 'Punjabi',
      nativeName: 'ਪੰਜਾਬੀ',
      region: 'Asia',
      script: 'Gurmukhi',
      countryEmoji: '🇮🇳',
      isPopular: true,
      sortOrder: 10,
    ),

    // European Languages
    Language(
      code: 'fr',
      name: 'French',
      nativeName: 'Français',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇫🇷',
      sortOrder: 11,
    ),
    Language(
      code: 'de',
      name: 'German',
      nativeName: 'Deutsch',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇩🇪',
      sortOrder: 12,
    ),
    Language(
      code: 'it',
      name: 'Italian',
      nativeName: 'Italiano',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇮🇹',
      sortOrder: 13,
    ),
    Language(
      code: 'nl',
      name: 'Dutch',
      nativeName: 'Nederlands',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇳🇱',
      sortOrder: 14,
    ),
    Language(
      code: 'sv',
      name: 'Swedish',
      nativeName: 'Svenska',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇸🇪',
      sortOrder: 15,
    ),
    Language(
      code: 'da',
      name: 'Danish',
      nativeName: 'Dansk',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇩🇰',
      sortOrder: 16,
    ),
    Language(
      code: 'no',
      name: 'Norwegian',
      nativeName: 'Norsk',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇳🇴',
      sortOrder: 17,
    ),
    Language(
      code: 'fi',
      name: 'Finnish',
      nativeName: 'Suomi',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇫🇮',
      sortOrder: 18,
    ),
    Language(
      code: 'pl',
      name: 'Polish',
      nativeName: 'Polski',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇵🇱',
      sortOrder: 19,
    ),
    Language(
      code: 'tr',
      name: 'Turkish',
      nativeName: 'Türkçe',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇹🇷',
      sortOrder: 20,
    ),
    Language(
      code: 'el',
      name: 'Greek',
      nativeName: 'Ελληνικά',
      region: 'Europe',
      script: 'Greek',
      countryEmoji: '🇬🇷',
      sortOrder: 21,
    ),
    Language(
      code: 'cs',
      name: 'Czech',
      nativeName: 'Čeština',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇨🇿',
      sortOrder: 22,
    ),
    Language(
      code: 'hu',
      name: 'Hungarian',
      nativeName: 'Magyar',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇭🇺',
      sortOrder: 23,
    ),
    Language(
      code: 'ro',
      name: 'Romanian',
      nativeName: 'Română',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇷🇴',
      sortOrder: 24,
    ),
    Language(
      code: 'bg',
      name: 'Bulgarian',
      nativeName: 'Български',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇧🇬',
      sortOrder: 25,
    ),
    Language(
      code: 'hr',
      name: 'Croatian',
      nativeName: 'Hrvatski',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇭🇷',
      sortOrder: 26,
    ),
    Language(
      code: 'sk',
      name: 'Slovak',
      nativeName: 'Slovenčina',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇸🇰',
      sortOrder: 27,
    ),
    Language(
      code: 'sl',
      name: 'Slovenian',
      nativeName: 'Slovenščina',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇸🇮',
      sortOrder: 28,
    ),
    Language(
      code: 'et',
      name: 'Estonian',
      nativeName: 'Eesti',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇪🇪',
      sortOrder: 29,
    ),
    Language(
      code: 'lv',
      name: 'Latvian',
      nativeName: 'Latviešu',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇱🇻',
      sortOrder: 30,
    ),
    Language(
      code: 'lt',
      name: 'Lithuanian',
      nativeName: 'Lietuvių',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇱🇹',
      sortOrder: 31,
    ),
    Language(
      code: 'uk',
      name: 'Ukrainian',
      nativeName: 'Українська',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇺🇦',
      sortOrder: 32,
    ),
    Language(
      code: 'be',
      name: 'Belarusian',
      nativeName: 'Беларуская',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇧🇾',
      sortOrder: 33,
    ),
    Language(
      code: 'sr',
      name: 'Serbian',
      nativeName: 'Српски',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇷🇸',
      sortOrder: 34,
    ),
    Language(
      code: 'mk',
      name: 'Macedonian',
      nativeName: 'Македонски',
      region: 'Europe',
      script: 'Cyrillic',
      countryEmoji: '🇲🇰',
      sortOrder: 35,
    ),
    Language(
      code: 'sq',
      name: 'Albanian',
      nativeName: 'Shqip',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇦🇱',
      sortOrder: 36,
    ),
    Language(
      code: 'mt',
      name: 'Maltese',
      nativeName: 'Malti',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇲🇹',
      sortOrder: 37,
    ),
    Language(
      code: 'is',
      name: 'Icelandic',
      nativeName: 'Íslenska',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇮🇸',
      sortOrder: 38,
    ),
    Language(
      code: 'ga',
      name: 'Irish',
      nativeName: 'Gaeilge',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇮🇪',
      sortOrder: 39,
    ),
    Language(
      code: 'cy',
      name: 'Welsh',
      nativeName: 'Cymraeg',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇬🇧',
      sortOrder: 40,
    ),
    Language(
      code: 'eu',
      name: 'Basque',
      nativeName: 'Euskera',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇪🇸',
      sortOrder: 41,
    ),
    Language(
      code: 'ca',
      name: 'Catalan',
      nativeName: 'Català',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇪🇸',
      sortOrder: 42,
    ),
    Language(
      code: 'gl',
      name: 'Galician',
      nativeName: 'Galego',
      region: 'Europe',
      script: 'Latin',
      countryEmoji: '🇪🇸',
      sortOrder: 43,
    ),

    // Asian Languages
    Language(
      code: 'ko',
      name: 'Korean',
      nativeName: '한국어',
      region: 'Asia',
      script: 'Hangul',
      countryEmoji: '🇰🇷',
      sortOrder: 44,
    ),
    Language(
      code: 'th',
      name: 'Thai',
      nativeName: 'ไทย',
      region: 'Asia',
      script: 'Thai',
      countryEmoji: '🇹🇭',
      sortOrder: 45,
    ),
    Language(
      code: 'vi',
      name: 'Vietnamese',
      nativeName: 'Tiếng Việt',
      region: 'Asia',
      script: 'Latin',
      countryEmoji: '🇻🇳',
      sortOrder: 46,
    ),
    Language(
      code: 'id',
      name: 'Indonesian',
      nativeName: 'Bahasa Indonesia',
      region: 'Asia',
      script: 'Latin',
      countryEmoji: '🇮🇩',
      sortOrder: 47,
    ),
    Language(
      code: 'ms',
      name: 'Malay',
      nativeName: 'Bahasa Melayu',
      region: 'Asia',
      script: 'Latin',
      countryEmoji: '🇲🇾',
      sortOrder: 48,
    ),
    Language(
      code: 'tl',
      name: 'Filipino',
      nativeName: 'Filipino',
      region: 'Asia',
      script: 'Latin',
      countryEmoji: '🇵🇭',
      sortOrder: 49,
    ),
    Language(
      code: 'ta',
      name: 'Tamil',
      nativeName: 'தமிழ்',
      region: 'Asia',
      script: 'Tamil',
      countryEmoji: '🇮🇳',
      sortOrder: 50,
    ),
    Language(
      code: 'te',
      name: 'Telugu',
      nativeName: 'తెలుగు',
      region: 'Asia',
      script: 'Telugu',
      countryEmoji: '🇮🇳',
      sortOrder: 51,
    ),
    Language(
      code: 'ml',
      name: 'Malayalam',
      nativeName: 'മലയാളം',
      region: 'Asia',
      script: 'Malayalam',
      countryEmoji: '🇮🇳',
      sortOrder: 52,
    ),
    Language(
      code: 'kn',
      name: 'Kannada',
      nativeName: 'ಕನ್ನಡ',
      region: 'Asia',
      script: 'Kannada',
      countryEmoji: '🇮🇳',
      sortOrder: 53,
    ),
    Language(
      code: 'gu',
      name: 'Gujarati',
      nativeName: 'ગુજરાતી',
      region: 'Asia',
      script: 'Gujarati',
      countryEmoji: '🇮🇳',
      sortOrder: 54,
    ),
    Language(
      code: 'mr',
      name: 'Marathi',
      nativeName: 'मराठी',
      region: 'Asia',
      script: 'Devanagari',
      countryEmoji: '🇮🇳',
      sortOrder: 55,
    ),
    Language(
      code: 'ur',
      name: 'Urdu',
      nativeName: 'اردو',
      region: 'Asia',
      script: 'Arabic',
      countryEmoji: '🇵🇰',
      sortOrder: 56,
    ),
    Language(
      code: 'fa',
      name: 'Persian',
      nativeName: 'فارسی',
      region: 'Asia',
      script: 'Arabic',
      countryEmoji: '🇮🇷',
      sortOrder: 57,
    ),
    Language(
      code: 'he',
      name: 'Hebrew',
      nativeName: 'עברית',
      region: 'Asia',
      script: 'Hebrew',
      countryEmoji: '🇮🇱',
      sortOrder: 58,
    ),

    // African Languages
    Language(
      code: 'sw',
      name: 'Swahili',
      nativeName: 'Kiswahili',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇹🇿',
      sortOrder: 59,
    ),
    Language(
      code: 'am',
      name: 'Amharic',
      nativeName: 'አማርኛ',
      region: 'Africa',
      script: 'Ethiopic',
      countryEmoji: '🇪🇹',
      sortOrder: 60,
    ),
    Language(
      code: 'ha',
      name: 'Hausa',
      nativeName: 'Hausa',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇳🇬',
      sortOrder: 61,
    ),
    Language(
      code: 'yo',
      name: 'Yoruba',
      nativeName: 'Yorùbá',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇳🇬',
      sortOrder: 62,
    ),
    Language(
      code: 'ig',
      name: 'Igbo',
      nativeName: 'Igbo',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇳🇬',
      sortOrder: 63,
    ),
    Language(
      code: 'zu',
      name: 'Zulu',
      nativeName: 'IsiZulu',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇿🇦',
      sortOrder: 64,
    ),
    Language(
      code: 'xh',
      name: 'Xhosa',
      nativeName: 'IsiXhosa',
      region: 'Africa',
      script: 'Latin',
      countryEmoji: '🇿🇦',
      sortOrder: 65,
    ),

    // American Languages
    Language(
      code: 'pt-BR',
      name: 'Portuguese (Brazil)',
      nativeName: 'Português (Brasil)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇧🇷',
      sortOrder: 66,
    ),
    Language(
      code: 'es-MX',
      name: 'Spanish (Mexico)',
      nativeName: 'Español (México)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇲🇽',
      sortOrder: 67,
    ),
    Language(
      code: 'es-AR',
      name: 'Spanish (Argentina)',
      nativeName: 'Español (Argentina)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇦🇷',
      sortOrder: 68,
    ),
    Language(
      code: 'es-CO',
      name: 'Spanish (Colombia)',
      nativeName: 'Español (Colombia)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇨🇴',
      sortOrder: 69,
    ),
    Language(
      code: 'es-PE',
      name: 'Spanish (Peru)',
      nativeName: 'Español (Perú)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇵🇪',
      sortOrder: 70,
    ),
    Language(
      code: 'es-VE',
      name: 'Spanish (Venezuela)',
      nativeName: 'Español (Venezuela)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇻🇪',
      sortOrder: 71,
    ),
    Language(
      code: 'es-CL',
      name: 'Spanish (Chile)',
      nativeName: 'Español (Chile)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇨🇱',
      sortOrder: 72,
    ),
    Language(
      code: 'es-UY',
      name: 'Spanish (Uruguay)',
      nativeName: 'Español (Uruguay)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇺🇾',
      sortOrder: 73,
    ),
    Language(
      code: 'es-PY',
      name: 'Spanish (Paraguay)',
      nativeName: 'Español (Paraguay)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇵🇾',
      sortOrder: 74,
    ),
    Language(
      code: 'es-BO',
      name: 'Spanish (Bolivia)',
      nativeName: 'Español (Bolivia)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇧🇴',
      sortOrder: 75,
    ),
    Language(
      code: 'es-EC',
      name: 'Spanish (Ecuador)',
      nativeName: 'Español (Ecuador)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇪🇨',
      sortOrder: 76,
    ),
    Language(
      code: 'es-GT',
      name: 'Spanish (Guatemala)',
      nativeName: 'Español (Guatemala)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇬🇹',
      sortOrder: 77,
    ),
    Language(
      code: 'es-CU',
      name: 'Spanish (Cuba)',
      nativeName: 'Español (Cuba)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇨🇺',
      sortOrder: 78,
    ),
    Language(
      code: 'es-DO',
      name: 'Spanish (Dominican Republic)',
      nativeName: 'Español (República Dominicana)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇩🇴',
      sortOrder: 79,
    ),
    Language(
      code: 'es-HN',
      name: 'Spanish (Honduras)',
      nativeName: 'Español (Honduras)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇭🇳',
      sortOrder: 80,
    ),
    Language(
      code: 'es-NI',
      name: 'Spanish (Nicaragua)',
      nativeName: 'Español (Nicaragua)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇳🇮',
      sortOrder: 81,
    ),
    Language(
      code: 'es-CR',
      name: 'Spanish (Costa Rica)',
      nativeName: 'Español (Costa Rica)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇨🇷',
      sortOrder: 82,
    ),
    Language(
      code: 'es-PA',
      name: 'Spanish (Panama)',
      nativeName: 'Español (Panamá)',
      region: 'Americas',
      script: 'Latin',
      countryEmoji: '🇵🇦',
      sortOrder: 83,
    ),
  ];

  /// Get all supported languages
  static List<Language> getAllLanguages() {
    return List.from(_languages);
  }

  /// Get popular languages (top 10)
  static List<Language> getPopularLanguages() {
    return _languages.where((lang) => lang.isPopular).toList();
  }

  /// Get languages by region
  static List<Language> getLanguagesByRegion(String region) {
    return _languages.where((lang) => lang.region == region).toList();
  }

  /// Get languages by script
  static List<Language> getLanguagesByScript(String script) {
    return _languages.where((lang) => lang.script == script).toList();
  }

  /// Get language by code
  static Language? getLanguageByCode(String code) {
    try {
      return _languages.firstWhere((lang) => lang.code == code);
    } catch (e) {
      return null;
    }
  }

  /// Search languages by name or native name
  static List<Language> searchLanguages(String query) {
    if (query.isEmpty) return getAllLanguages();
    
    final lowercaseQuery = query.toLowerCase();
    return _languages.where((lang) {
      return lang.name.toLowerCase().contains(lowercaseQuery) ||
             lang.nativeName.toLowerCase().contains(lowercaseQuery) ||
             lang.code.toLowerCase().contains(lowercaseQuery);
    }).toList();
  }

  /// Get all unique regions
  static List<String> getAllRegions() {
    return _languages.map((lang) => lang.region).toSet().toList()..sort();
  }

  /// Get all unique scripts
  static List<String> getAllScripts() {
    return _languages.map((lang) => lang.script).toSet().toList()..sort();
  }

  /// Check if language code is supported
  static bool isLanguageSupported(String code) {
    return _languages.any((lang) => lang.code == code);
  }

  /// Get default language (English)
  static Language getDefaultLanguage() {
    return getLanguageByCode('en')!;
  }
}